"""
staging.py — Persistent playlist staging shelf.

Playlists are stored as JSON files in staging/playlists/{uuid}.json
and persist between sessions. Users build up a shelf of playlists,
then batch-deploy or deploy individually.

Each staged playlist has this structure:
{
    "id": "uuid4",
    "suggested_name": "Brazilian Phonk",   # generated by namer
    "user_name": "",                         # set by user, falls back to suggested_name
    "description": "32 tracks...",
    "track_uris": [...],
    "rec_uris": [],                          # populated when expand_with_recs=True
    "expand_with_recs": False,
    "cohesion": 0.84,
    "genre_breakdown": {"Brazilian Phonk": 0.60},
    "source_type": "genre" | "mood" | "era" | "artist",
    "source_label": "Brazilian Phonk",
    "created_at": "ISO timestamp",
    "deployed": False,
    "deployed_at": None,
    "spotify_url": None,
}
"""

import json
import os
import uuid
from datetime import datetime, timezone
from typing import Optional

import config


def _ensure_dir() -> str:
    """Ensure the staging directory exists and return its path."""
    path = config.STAGING_DIR
    os.makedirs(path, exist_ok=True)
    return path


def _playlist_path(playlist_id: str) -> str:
    """Return the file path for a staged playlist by ID."""
    return os.path.join(_ensure_dir(), f"{playlist_id}.json")


def _atomic_write_json(path: str, data: dict) -> None:
    """
    Write JSON to disk atomically via temp-file + os.replace().

    Prevents corruption if the process is interrupted (crash, Ctrl+C, power
    loss) mid-write. Without this, a half-written file looks like a valid
    path but fails to parse, which load_all() silently skips — user sees
    their playlist vanish.

    Note: os.replace() is atomic on POSIX and atomic-enough on Windows
    (Win32 MoveFileEx with MOVEFILE_REPLACE_EXISTING).
    """
    tmp_path = f"{path}.tmp"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.flush()
        try:
            os.fsync(f.fileno())
        except OSError:
            pass  # some filesystems (network mounts) don't support fsync
    os.replace(tmp_path, path)


def _new_playlist(data: dict) -> dict:
    """
    Merge provided data into a full playlist record with all required fields
    and sane defaults.
    """
    now = datetime.now(timezone.utc).isoformat()
    record = {
        "id":               str(uuid.uuid4()),
        "suggested_name":   "",
        "user_name":        "",
        "description":      "",
        "track_uris":       [],
        "rec_uris":         [],
        "expand_with_recs": False,
        "cohesion":         0.0,
        "genre_breakdown":  {},
        "source_type":      "genre",
        "source_label":     "",
        "created_at":       now,
        "deployed":         False,
        "deployed_at":      None,
        "spotify_url":      None,
    }
    record.update(data)
    # Force the ID from data if provided, else use newly generated
    if "id" not in data:
        pass  # already set above
    return record


def save(playlist_dict: dict) -> str:
    """
    Save a playlist to the staging shelf.

    If the dict has an "id" field that already exists, updates in place.
    Otherwise creates a new record with a generated UUID.

    Args:
        playlist_dict: Partial or full playlist record.

    Returns:
        The playlist ID string.
    """
    existing_id = playlist_dict.get("id")
    if existing_id and os.path.exists(_playlist_path(existing_id)):
        # Update existing
        existing = load(existing_id) or {}
        existing.update(playlist_dict)
        record = existing
    else:
        record = _new_playlist(playlist_dict)

    path = _playlist_path(record["id"])
    _atomic_write_json(path, record)

    return record["id"]


def load(playlist_id: str) -> Optional[dict]:
    """
    Load a single staged playlist by ID.

    Returns:
        The playlist dict, or None if not found.
    """
    path = _playlist_path(playlist_id)
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def load_all() -> list[dict]:
    """
    Load all staged (not yet deployed) playlists, sorted by created_at descending.

    Returns:
        List of playlist dicts where deployed == False.

    Note:
        Corrupt playlist files (caused by e.g. an interrupted pre-atomic-write
        save) are quarantined by appending ``.corrupt`` to the filename so the
        user can see something went wrong instead of assuming the playlist
        just vanished.
    """
    staging_dir = _ensure_dir()
    playlists = []
    for fname in os.listdir(staging_dir):
        if not fname.endswith(".json"):
            continue
        fpath = os.path.join(staging_dir, fname)
        try:
            with open(fpath, "r", encoding="utf-8") as f:
                data = json.load(f)
            if not data.get("deployed", False):
                playlists.append(data)
        except json.JSONDecodeError:
            # Quarantine corrupt JSON so it's visible on disk instead of
            # silently vanishing from the staging shelf.
            try:
                os.rename(fpath, f"{fpath}.corrupt")
            except OSError:
                pass
            continue
        except OSError:
            continue

    playlists.sort(key=lambda p: p.get("created_at", ""), reverse=True)
    return playlists


def get_all_including_deployed() -> list[dict]:
    """
    Load ALL staged playlists including already-deployed ones.

    Returns:
        List of all playlist dicts, sorted by created_at descending.
    """
    staging_dir = _ensure_dir()
    playlists = []
    for fname in os.listdir(staging_dir):
        if not fname.endswith(".json"):
            continue
        fpath = os.path.join(staging_dir, fname)
        try:
            with open(fpath, "r", encoding="utf-8") as f:
                data = json.load(f)
            playlists.append(data)
        except (json.JSONDecodeError, OSError):
            continue

    playlists.sort(key=lambda p: p.get("created_at", ""), reverse=True)
    return playlists


def update(playlist_id: str, updates: dict) -> dict:
    """
    Apply a partial update to a staged playlist.

    Args:
        playlist_id: The playlist ID to update.
        updates:     Dict of fields to update.

    Returns:
        The updated playlist dict.

    Raises:
        KeyError: If the playlist ID is not found.
    """
    record = load(playlist_id)
    if record is None:
        raise KeyError(f"Staged playlist not found: {playlist_id}")
    record.update(updates)
    path = _playlist_path(playlist_id)
    _atomic_write_json(path, record)
    return record


def delete(playlist_id: str) -> bool:
    """
    Delete a staged playlist from the shelf.

    Args:
        playlist_id: The playlist ID to delete.

    Returns:
        True if deleted, False if not found.
    """
    path = _playlist_path(playlist_id)
    if not os.path.exists(path):
        return False
    os.remove(path)
    return True


def mark_deployed(playlist_id: str, spotify_url: str) -> None:
    """
    Mark a staged playlist as deployed and record the Spotify URL.

    Args:
        playlist_id:  The playlist ID.
        spotify_url:  The Spotify playlist URL returned after creation.
    """
    now = datetime.now(timezone.utc).isoformat()
    update(playlist_id, {
        "deployed":     True,
        "deployed_at":  now,
        "spotify_url":  spotify_url,
    })


def get_staged_count() -> int:
    """
    Return the count of playlists not yet deployed.

    Returns:
        Integer count.
    """
    return len(load_all())


def get_display_name(staged: dict) -> str:
    """
    Return the effective display name for a staged playlist.
    Prefers user_name if set, falls back to suggested_name.

    Args:
        staged: A staged playlist dict.

    Returns:
        The name string to display.
    """
    return (staged.get("user_name") or staged.get("suggested_name") or "Untitled Playlist").strip()
