"""One-time script: expand all thin anchor sets to 6 tracks with correct picks."""
import json

anchors = json.load(open("data/mood_anchors.json", encoding="utf-8"))

additions = {
    "Amapiano Sunset": [
        {"artist": "Kabza De Small", "title": "Sponono"},
        {"artist": "Focalistic", "title": "Ke Star"},
        {"artist": "DJ Maphorisa", "title": "Izikhothane"},
        {"artist": "Ami Faku", "title": "Into Ingawe"},
        {"artist": "MaWhoo", "title": "Akulaleki"},
        {"artist": "Tyler ICU", "title": "Inhliziyo"},
    ],
    "Baroque Pop Melodrama": [
        {"artist": "Sufjan Stevens", "title": "Death With Dignity"},
        {"artist": "Regina Spektor", "title": "Samson"},
        {"artist": "The Decemberists", "title": "The Mariner's Revenge Song"},
        {"artist": "Joanna Newsom", "title": "Sprout and the Bean"},
        {"artist": "Sufjan Stevens", "title": "Futile Devices"},
        {"artist": "Beirut", "title": "Nantes"},
    ],
    "Brass & Drumline Energy": [
        {"artist": "Earth, Wind & Fire", "title": "September"},
        {"artist": "James Brown", "title": "Sex Machine"},
        {"artist": "Trombone Shorty", "title": "St. James Infirmary"},
        {"artist": "Tower of Power", "title": "What Is Hip"},
        {"artist": "Lettuce", "title": "Phyllis"},
        {"artist": "Galactic", "title": "Go Go"},
    ],
    "Country Roads": [
        {"artist": "John Denver", "title": "Take Me Home, Country Roads"},
        {"artist": "Johnny Cash", "title": "Ring of Fire"},
        {"artist": "Dolly Parton", "title": "Jolene"},
        {"artist": "Willie Nelson", "title": "On the Road Again"},
        {"artist": "Hank Williams", "title": "I'm So Lonesome I Could Cry"},
        {"artist": "Merle Haggard", "title": "Mama Tried"},
    ],
    "Country Story Hour": [
        {"artist": "Johnny Cash", "title": "Hurt"},
        {"artist": "Townes Van Zandt", "title": "Pancho and Lefty"},
        {"artist": "Gillian Welch", "title": "Everything Is Free"},
        {"artist": "Kris Kristofferson", "title": "Me and Bobby McGee"},
        {"artist": "Emmylou Harris", "title": "Boulder to Birmingham"},
        {"artist": "Iris DeMent", "title": "Our Town"},
    ],
    "Disco Lights": [
        {"artist": "Daft Punk", "title": "Get Lucky"},
        {"artist": "Bee Gees", "title": "Stayin' Alive"},
        {"artist": "Chic", "title": "Le Freak"},
        {"artist": "Gloria Gaynor", "title": "I Will Survive"},
        {"artist": "Donna Summer", "title": "Hot Stuff"},
        {"artist": "Village People", "title": "Y.M.C.A."},
    ],
    "Drill Confessions": [
        {"artist": "Pop Smoke", "title": "Dior"},
        {"artist": "Central Cee", "title": "Loading"},
        {"artist": "Dave", "title": "Location"},
        {"artist": "Lil Baby", "title": "Emotionally Scarred"},
        {"artist": "Fivio Foreign", "title": "Big Drip"},
        {"artist": "Headie One", "title": "Know Better"},
    ],
    "Flex Tape": [
        {"artist": "Drake", "title": "God's Plan"},
        {"artist": "Kendrick Lamar", "title": "HUMBLE."},
        {"artist": "Travis Scott", "title": "SICKO MODE"},
        {"artist": "Cardi B", "title": "Bodak Yellow"},
        {"artist": "Lil Uzi Vert", "title": "XO Tour Llif3"},
        {"artist": "Future", "title": "Mask Off"},
    ],
    "Golden Hour": [
        {"artist": "The Beatles", "title": "Twist And Shout"},
        {"artist": "Electric Light Orchestra", "title": "Mr. Blue Sky"},
        {"artist": "Natasha Bedingfield", "title": "Unwritten"},
        {"artist": "Pharrell Williams", "title": "Happy"},
        {"artist": "Cat Stevens", "title": "Here Comes My Baby"},
        {"artist": "Bill Withers", "title": "Lovely Day"},
    ],
    "Gospel Fire": [
        {"artist": "Kanye West", "title": "Jesus Walks"},
        {"artist": "Kirk Franklin", "title": "Stomp"},
        {"artist": "Hezekiah Walker", "title": "Every Praise"},
        {"artist": "Tasha Cobbs Leonard", "title": "Break Every Chain"},
        {"artist": "Lecrae", "title": "Tell the World"},
        {"artist": "Travis Greene", "title": "Intentional"},
    ],
    # Fix: Kanye West x3 in Healing Kind is wrong dominance
    "Healing Kind": [
        {"artist": "Bon Iver", "title": "Holocene"},
        {"artist": "Nick Drake", "title": "Pink Moon"},
        {"artist": "Iron & Wine", "title": "Naked As We Came"},
        {"artist": "Sufjan Stevens", "title": "Death With Dignity"},
        {"artist": "Fleet Foxes", "title": "White Winter Hymnal"},
        {"artist": "Jose Gonzalez", "title": "Heartbeats"},
    ],
    "Hyperpop": [
        {"artist": "100 gecs", "title": "money machine"},
        {"artist": "Charli XCX", "title": "Click"},
        {"artist": "SOPHIE", "title": "Immaterial"},
        {"artist": "Bladee", "title": "Icedancer"},
        {"artist": "Dorian Electra", "title": "Career Boy"},
        {"artist": "Drain Gang", "title": "Avalon"},
    ],
    "Indie Bedroom": [
        {"artist": "Rex Orange County", "title": "Television / So Far So Good"},
        {"artist": "Cavetown", "title": "Boys Will Be Bugs"},
        {"artist": "Tame Impala", "title": "Let It Happen"},
        {"artist": "Clairo", "title": "Pretty Girl"},
        {"artist": "Still Woozy", "title": "Goodie Bag"},
        {"artist": "girl in red", "title": "i wanna be your girlfriend"},
    ],
    "Industrial Gothic Floor": [
        {"artist": "Nine Inch Nails", "title": "Closer"},
        {"artist": "Rammstein", "title": "Du Hast"},
        {"artist": "Ministry", "title": "Jesus Built My Hotrod"},
        {"artist": "KMFDM", "title": "A Drug Against War"},
        {"artist": "Marilyn Manson", "title": "Beautiful People"},
        {"artist": "Rob Zombie", "title": "Dragula"},
    ],
    "J-Metal": [
        {"artist": "X Japan", "title": "Endless Rain"},
        {"artist": "Dir En Grey", "title": "Obscure"},
        {"artist": "Buck-Tick", "title": "Dress"},
        {"artist": "Luna Sea", "title": "Storm"},
        {"artist": "Gazette", "title": "Cassis"},
        {"artist": "Malice Mizer", "title": "Le Ciel"},
    ],
    "J-Pop": [
        {"artist": "Hikaru Utada", "title": "First Love"},
        {"artist": "Kenshi Yonezu", "title": "Lemon"},
        {"artist": "Kyary Pamyu Pamyu", "title": "PONPONPON"},
        {"artist": "Ado", "title": "Usseewa"},
        {"artist": "Official HIGE DANdism", "title": "Pretender"},
        {"artist": "YOASOBI", "title": "Idol"},
    ],
    "Latin Ballroom Heat": [
        {"artist": "Marc Anthony", "title": "Vivir Mi Vida"},
        {"artist": "Celia Cruz", "title": "La Vida Es Un Carnaval"},
        {"artist": "Buena Vista Social Club", "title": "Chan Chan"},
        {"artist": "Tito Puente", "title": "Oye Como Va"},
        {"artist": "Gloria Estefan", "title": "Conga"},
        {"artist": "Ruben Blades", "title": "Pedro Navaja"},
    ],
    "Latin Heat": [
        {"artist": "Bad Bunny", "title": "Dakiti"},
        {"artist": "J Balvin", "title": "Mi Gente"},
        {"artist": "Daddy Yankee", "title": "Gasolina"},
        {"artist": "Shakira", "title": "Hips Don't Lie"},
        {"artist": "Ozuna", "title": "Taki Taki"},
        {"artist": "Maluma", "title": "Hawai"},
    ],
    "Meditation Bath": [
        {"artist": "Brian Eno", "title": "Music for Airports 1/1"},
        {"artist": "Max Richter", "title": "On the Nature of Daylight"},
        {"artist": "Nils Frahm", "title": "Says"},
        {"artist": "Stars of the Lid", "title": "Requiem for Dying Mothers"},
        {"artist": "Moby", "title": "Why Does My Heart Feel So Bad"},
        {"artist": "Jon Hopkins", "title": "Open Eye Signal"},
    ],
    "Metal Testimony": [
        {"artist": "Skillet", "title": "Monster"},
        {"artist": "August Burns Red", "title": "White Washed"},
        {"artist": "Demon Hunter", "title": "The Soldier's Song"},
        {"artist": "Stryper", "title": "To Hell with the Devil"},
        {"artist": "Switchfoot", "title": "Dare You to Move"},
        {"artist": "POD", "title": "Alive"},
    ],
    "Minimal Techno Tunnel": [
        {"artist": "Richie Hawtin", "title": "Consumed"},
        {"artist": "Robert Hood", "title": "Moveable Parts"},
        {"artist": "Basic Channel", "title": "Phylyps Trak"},
        {"artist": "Surgeon", "title": "Force + Counterforce"},
        {"artist": "Ben Klock", "title": "One"},
        {"artist": "Planetary Assault Systems", "title": "The Messenger"},
    ],
    "Money Talks": [
        {"artist": "Jay-Z", "title": "99 Problems"},
        {"artist": "Rick Ross", "title": "Hustlin'"},
        {"artist": "Kanye West", "title": "Gold Digger"},
        {"artist": "Drake", "title": "Started From the Bottom"},
        {"artist": "Lil Wayne", "title": "A Milli"},
        {"artist": "50 Cent", "title": "In da Club"},
    ],
    # Fix: Morning Ritual had indie/chill songs, should be upbeat morning energy
    "Morning Ritual": [
        {"artist": "Vampire Weekend", "title": "A-Punk"},
        {"artist": "Beach Boys", "title": "Good Vibrations"},
        {"artist": "Jack Johnson", "title": "Better Together"},
        {"artist": "Mac DeMarco", "title": "Chamber of Reflection"},
        {"artist": "Paulo Nutini", "title": "New Shoes"},
        {"artist": "Ben Harper", "title": "Steal My Kisses"},
    ],
    "Neo-Soul": [
        {"artist": "D'Angelo", "title": "Brown Sugar"},
        {"artist": "Erykah Badu", "title": "On & On"},
        {"artist": "Lauryn Hill", "title": "Ex-Factor"},
        {"artist": "John Legend", "title": "Ordinary People"},
        {"artist": "Maxwell", "title": "Ascension"},
        {"artist": "Anthony Hamilton", "title": "Charlene"},
    ],
    "Open Road": [
        {"artist": "Tom Cochrane", "title": "Life Is a Highway"},
        {"artist": "Bruce Springsteen", "title": "Born to Run"},
        {"artist": "Eagles", "title": "Take It Easy"},
        {"artist": "Jackson Browne", "title": "Running on Empty"},
        {"artist": "Tom Petty", "title": "Free Fallin"},
        {"artist": "Chris Stapleton", "title": "Tennessee Whiskey"},
    ],
    "Overflow": [
        {"artist": "Radiohead", "title": "Creep"},
        {"artist": "The Neighbourhood", "title": "How"},
        {"artist": "The 1975", "title": "Be My Mistake"},
        {"artist": "Bon Iver", "title": "For Emma"},
        {"artist": "Elliott Smith", "title": "Between the Bars"},
        {"artist": "Bright Eyes", "title": "Lua"},
    ],
    "Overthinking": [
        {"artist": "The 1975", "title": "Be My Mistake"},
        {"artist": "The Neighbourhood", "title": "How"},
        {"artist": "Jeff Buckley", "title": "Hallelujah"},
        {"artist": "Radiohead", "title": "No Surprises"},
        {"artist": "Sufjan Stevens", "title": "Mystery of Love"},
        {"artist": "Julia Jacklin", "title": "Pressure to Party"},
    ],
    "Pluggnb Heartache": [
        {"artist": "SAINt JHN", "title": "Roses"},
        {"artist": "Metro Boomin", "title": "Space Cadet"},
        {"artist": "Lil Peep", "title": "Awful Things"},
        {"artist": "Juice WRLD", "title": "Lucid Dreams"},
        {"artist": "Rod Wave", "title": "Heart on Ice"},
        {"artist": "NF", "title": "The Search"},
    ],
    "Queer Dance Confetti": [
        {"artist": "ABBA", "title": "Dancing Queen"},
        {"artist": "Kylie Minogue", "title": "Can't Get You Out of My Head"},
        {"artist": "Madonna", "title": "Like a Prayer"},
        {"artist": "Lady Gaga", "title": "Born This Way"},
        {"artist": "Troye Sivan", "title": "YOUTH"},
        {"artist": "Kim Petras", "title": "Heart to Break"},
    ],
    "Raw Emotion": [
        {"artist": "The 1975", "title": "Be My Mistake"},
        {"artist": "Red Hot Chili Peppers", "title": "Scar Tissue"},
        {"artist": "Muse", "title": "Supermassive Black Hole"},
        {"artist": "Damien Rice", "title": "Delicate"},
        {"artist": "Hozier", "title": "Cherry Wine"},
        {"artist": "Frightened Rabbit", "title": "Modern Leper"},
    ],
    "Runaway Highways": [
        {"artist": "Tom Petty", "title": "Running Down a Dream"},
        {"artist": "Creedence Clearwater Revival", "title": "Born on the Bayou"},
        {"artist": "Eagles", "title": "Take It Easy"},
        {"artist": "Bruce Springsteen", "title": "Born to Run"},
        {"artist": "John Mellencamp", "title": "Pink Houses"},
        {"artist": "Lynyrd Skynyrd", "title": "Free Bird"},
    ],
    "Same Vibe Different Genre": [
        {"artist": "Radiohead", "title": "Creep"},
        {"artist": "Tame Impala", "title": "Let It Happen"},
        {"artist": "Kanye West", "title": "Gold Digger"},
        {"artist": "The Beatles", "title": "Come Together"},
        {"artist": "Billie Eilish", "title": "bad guy"},
        {"artist": "Tyler, the Creator", "title": "EARFQUAKE"},
    ],
    "Sea Shanty Singalong": [
        {"artist": "The Longest Johns", "title": "Wellerman"},
        {"artist": "Fisherman's Friends", "title": "South Australia"},
        {"artist": "Great Big Sea", "title": "The Old Black Rum"},
        {"artist": "Nathan Evans", "title": "Wellerman"},
        {"artist": "Alestorm", "title": "Drink"},
        {"artist": "Dropkick Murphys", "title": "Im Shipping Up to Boston"},
    ],
    "Slow Jams": [
        {"artist": "Usher", "title": "Nice and Slow"},
        {"artist": "Brian McKnight", "title": "Back at One"},
        {"artist": "Keith Sweat", "title": "I Want Her"},
        {"artist": "Ginuwine", "title": "Pony"},
        {"artist": "Jodeci", "title": "Cry for You"},
        {"artist": "Babyface", "title": "Every Time I Close My Eyes"},
    ],
    # Fix: Smoke & Mirrors — SadBoyProlific and Kanye Dark Fantasy are wrong
    "Smoke & Mirrors": [
        {"artist": "The Neighbourhood", "title": "How"},
        {"artist": "The Heavy", "title": "How You Like Me Now"},
        {"artist": "Arctic Monkeys", "title": "Why'd You Only Call Me When You're High"},
        {"artist": "Queens of the Stone Age", "title": "Go with the Flow"},
        {"artist": "Gorillaz", "title": "Clint Eastwood"},
        {"artist": "Beck", "title": "Loser"},
    ],
    "Songs About Goodbye": [
        {"artist": "The 1975", "title": "Be My Mistake"},
        {"artist": "Jeff Buckley", "title": "Hallelujah"},
        {"artist": "The Neighbourhood", "title": "R.I.P. 2 My Youth"},
        {"artist": "Green Day", "title": "Good Riddance"},
        {"artist": "Semisonic", "title": "Closing Time"},
        {"artist": "Death Cab for Cutie", "title": "I Will Follow You into the Dark"},
    ],
    "Sunday Reset": [
        {"artist": "Rex Orange County", "title": "Television / So Far So Good"},
        {"artist": "Jack Johnson", "title": "Better Together"},
        {"artist": "Sufjan Stevens", "title": "Mystery of Love"},
        {"artist": "Novo Amor", "title": "Anchor"},
        {"artist": "Hozier", "title": "From Eden"},
        {"artist": "JP Cooper", "title": "September Song"},
    ],
    "Sundown": [
        {"artist": "Tame Impala", "title": "Eventually"},
        {"artist": "Fleetwood Mac", "title": "The Chain"},
        {"artist": "Eagles", "title": "Peaceful Easy Feeling"},
        {"artist": "Dire Straits", "title": "Sultans of Swing"},
        {"artist": "Joni Mitchell", "title": "Big Yellow Taxi"},
        {"artist": "James Taylor", "title": "Fire and Rain"},
    ],
    "Symphonic Metal Epics": [
        {"artist": "Epica", "title": "Consign to Oblivion"},
        {"artist": "Nightwish", "title": "Ghost Love Score"},
        {"artist": "Within Temptation", "title": "Ice Queen"},
        {"artist": "Apocalyptica", "title": "Nothing Else Matters"},
        {"artist": "Evanescence", "title": "Bring Me to Life"},
        {"artist": "Tarja", "title": "I Walk Alone"},
    ],
    "Warehouse Techno": [
        {"artist": "Jeff Mills", "title": "The Bells"},
        {"artist": "Adam Beyer", "title": "Drums Please"},
        {"artist": "Amelie Lens", "title": "Exhale"},
        {"artist": "Surgeon", "title": "Force + Counterforce"},
        {"artist": "Charlotte de Witte", "title": "Sgat"},
        {"artist": "Svreca", "title": "Naked Lunch"},
    ],
}

for mood_name, new_anchors in additions.items():
    anchors[mood_name] = new_anchors

with open("data/mood_anchors.json", "w", encoding="utf-8") as f:
    json.dump(anchors, f, ensure_ascii=False, indent=2)

total = sum(len(a) for a in anchors.values())
avg = total / len(anchors)
thin = sum(1 for a in anchors.values() if len(a) < 5)
print(f"Saved. Total anchors: {total}, avg: {avg:.1f}, still <5: {thin}")
for m, a in sorted(anchors.items(), key=lambda x: len(x[1])):
    if len(a) < 5:
        print(f"  STILL THIN: {m}: {len(a)}")
