#!/usr/bin/env python3
"""
patch_packs.py
- Adds vibe_sentence and anti_mood to all 87 existing moods
- Adds 23 new mood packs with complete definitions
- Writes the updated packs.json back
"""

import json
import os

PACKS_PATH = os.path.join(os.path.dirname(__file__), "..", "data", "packs.json")

# ---------------------------------------------------------------------------
# TASK 1: vibe_sentence + anti_mood for all 87 existing moods
# ---------------------------------------------------------------------------

EXISTING_MOOD_PATCHES = {
    "Late Night Drive": {
        "vibe_sentence": "Windows down, city blurring, nowhere to be.",
        "anti_mood": ["Morning Ritual", "Gospel Fire", "Overflow"],
    },
    "Hollow": {
        "vibe_sentence": "You're not sad. You're just completely empty.",
        "anti_mood": ["Overflow", "Gospel Fire", "Golden Hour"],
    },
    "Overflow": {
        "vibe_sentence": "This is the moment you've been waiting for all year.",
        "anti_mood": ["Hollow", "Liminal", "Rainy Window"],
    },
    "Adrenaline": {
        "vibe_sentence": "No ceiling, no brakes, just output.",
        "anti_mood": ["Meditation Bath", "Sunday Reset", "Classical Calm"],
    },
    "Villain Arc": {
        "vibe_sentence": "You're not apologizing. You're arriving.",
        "anti_mood": ["Gospel Fire", "Healing Kind", "Morning Ritual"],
    },
    "Golden Hour": {
        "vibe_sentence": "That specific light where everything looks like it matters.",
        "anti_mood": ["Hollow", "Liminal", "Goth / Darkwave"],
    },
    "Weightless": {
        "vibe_sentence": "Your body forgot it had weight. Float with it.",
        "anti_mood": ["Adrenaline", "Hard Reset", "Phonk Season"],
    },
    "Deep Focus": {
        "vibe_sentence": "The world disappeared. Just you and the work.",
        "anti_mood": ["Overflow", "Euphoric Rave", "Adrenaline"],
    },
    "Afterparty": {
        "vibe_sentence": "Still going at 4am because nobody wants it to end.",
        "anti_mood": ["Morning Ritual", "Classical Calm", "Meditation Bath"],
    },
    "Euphoric Rave": {
        "vibe_sentence": "Lights off, four-on-the-floor, and you are the crowd.",
        "anti_mood": ["Rainy Window", "Hollow", "Classical Calm"],
    },
    "Morning Ritual": {
        "vibe_sentence": "Coffee steam rising. The day hasn't broken you yet.",
        "anti_mood": ["Afterparty", "Midnight Clarity", "Overthinking"],
    },
    "Nostalgia": {
        "vibe_sentence": "Songs that feel like a memory even the first time.",
        "anti_mood": ["Hyperpop", "Euphoric Rave", "K-Pop Zone"],
    },
    "Acoustic Corner": {
        "vibe_sentence": "Just the song. Nothing else needs to be here.",
        "anti_mood": ["Euphoric Rave", "Hard Reset", "K-Pop Zone"],
    },
    "Overthinking": {
        "vibe_sentence": "Every conversation you didn't handle right, on shuffle.",
        "anti_mood": ["Morning Ritual", "Overflow", "Golden Hour"],
    },
    "Smoke & Mirrors": {
        "vibe_sentence": "Low lights, slow burn, nobody has to go home yet.",
        "anti_mood": ["Morning Ritual", "Adrenaline", "Gospel Fire"],
    },
    "Tropicana": {
        "vibe_sentence": "Heat on skin, rhythm in bones, whole world on one floor.",
        "anti_mood": ["Rainy Window", "Hollow", "Classical Calm"],
    },
    "Soft Hours": {
        "vibe_sentence": "Everything needs to be gentle right now. Let it.",
        "anti_mood": ["Adrenaline", "Hard Reset", "Euphoric Rave"],
    },
    "Midnight Clarity": {
        "vibe_sentence": "4am made everything obvious and terrifying at once.",
        "anti_mood": ["Morning Ritual", "K-Pop Zone", "Tropicana"],
    },
    "Phonk Season": {
        "vibe_sentence": "Cowbell and darkness and you are drifting through all of it.",
        "anti_mood": ["Morning Ritual", "Gospel Fire", "Soft Hours"],
    },
    "Raw Emotion": {
        "vibe_sentence": "No polish. Just the feeling, uncut and loud.",
        "anti_mood": ["Deep Focus", "Sunday Reset", "Meditation Bath"],
    },
    "Liminal": {
        "vibe_sentence": "Empty airport, 4am. The world between worlds.",
        "anti_mood": ["Overflow", "Golden Hour", "Tropicana"],
    },
    "Open Road": {
        "vibe_sentence": "No destination. Just the highway and the volume.",
        "anti_mood": ["Meditation Bath", "Deep Focus", "Hollow"],
    },
    "Sundown": {
        "vibe_sentence": "End of day, slow exhale, still in one piece.",
        "anti_mood": ["Adrenaline", "Euphoric Rave", "Hard Reset"],
    },
    "Flex Tape": {
        "vibe_sentence": "Loud, arrogant, and completely unapologetic about it.",
        "anti_mood": ["Hollow", "Rainy Window", "Acoustic Corner"],
    },
    "Hard Reset": {
        "vibe_sentence": "Volume as medicine. Scream it out, start clean.",
        "anti_mood": ["Morning Ritual", "Soft Hours", "Meditation Bath"],
    },
    "Dark Pop": {
        "vibe_sentence": "Pop aesthetics wearing shadow like a second skin.",
        "anti_mood": ["Gospel Fire", "K-Pop Zone", "Overflow"],
    },
    "Slow Jams": {
        "vibe_sentence": "Bedroom lighting, no clock, just the two of you.",
        "anti_mood": ["Adrenaline", "Hard Reset", "Punk Sprint"],
    },
    "Emo Hour": {
        "vibe_sentence": "Every feeling at maximum volume, and it still isn't enough.",
        "anti_mood": ["Golden Hour", "Gospel Fire", "Disco Lights"],
    },
    "Jazz Nights": {
        "vibe_sentence": "Smoky room, slow swing, music that knows more than you do.",
        "anti_mood": ["Euphoric Rave", "Hard Reset", "K-Pop Zone"],
    },
    "Drill": {
        "vibe_sentence": "Cold melody, sliding 808, no warmth intended.",
        "anti_mood": ["Morning Ritual", "Gospel Fire", "Sunday Reset"],
    },
    "Neo-Soul": {
        "vibe_sentence": "Warm bass, conscious groove, music that nourishes the chest.",
        "anti_mood": ["Hard Reset", "Phonk Season", "Euphoric Rave"],
    },
    "Psychedelic": {
        "vibe_sentence": "Layers upon layers. Time started doing something strange.",
        "anti_mood": ["Deep Focus", "Drill", "Classical Calm"],
    },
    "Heartbreak": {
        "vibe_sentence": "You're not crying. You're seething. There's a difference.",
        "anti_mood": ["Overflow", "Gospel Fire", "Golden Hour"],
    },
    "Indie Bedroom": {
        "vibe_sentence": "Music that feels like it was made in your room, for your room.",
        "anti_mood": ["Euphoric Rave", "K-Pop Zone", "Adrenaline"],
    },
    "Country Roads": {
        "vibe_sentence": "Honest words, dusty boots, and an open sky saying nothing.",
        "anti_mood": ["Euphoric Rave", "Warehouse Techno", "Phonk Season"],
    },
    "Gospel Fire": {
        "vibe_sentence": "The kind of joy that makes your chest hurt.",
        "anti_mood": ["Hollow", "Drill", "Goth / Darkwave"],
    },
    "Old School Hip-Hop": {
        "vibe_sentence": "Boom bap, dusty samples, bars that actually mean something.",
        "anti_mood": ["Classical Calm", "Meditation Bath", "Weightless"],
    },
    "K-Pop Zone": {
        "vibe_sentence": "Choreographed chaos, perfect hooks, no apologies for the glitter.",
        "anti_mood": ["Goth / Darkwave", "Hard Reset", "Rainy Window"],
    },
    "Sunday Reset": {
        "vibe_sentence": "Nothing urgent. Nothing heavy. Just exist for a while.",
        "anti_mood": ["Adrenaline", "Euphoric Rave", "Hard Reset"],
    },
    "Synthwave Nights": {
        "vibe_sentence": "Neon grid, chrome city, driving through a future that never happened.",
        "anti_mood": ["Acoustic Corner", "Country Roads", "Gospel Fire"],
    },
    "Hyperpop": {
        "vibe_sentence": "Too much of everything — and somehow that's exactly right.",
        "anti_mood": ["Classical Calm", "Meditation Bath", "Jazz Nights"],
    },
    "Goth / Darkwave": {
        "vibe_sentence": "Beautiful desolation in a black coat on a dark dancefloor.",
        "anti_mood": ["K-Pop Zone", "Gospel Fire", "Tropicana"],
    },
    "Lo-Fi Flow": {
        "vibe_sentence": "Head down, dusty drums, the work happening one bar at a time.",
        "anti_mood": ["Adrenaline", "Euphoric Rave", "Hard Reset"],
    },
    "Rainy Window": {
        "vibe_sentence": "Grey sky, warm mug, songs that hug the quiet.",
        "anti_mood": ["Adrenaline", "Overflow", "Tropicana"],
    },
    "Latin Heat": {
        "vibe_sentence": "Dembow in your bones, sun on your skin, floor beneath your feet.",
        "anti_mood": ["Rainy Window", "Classical Calm", "Meditation Bath"],
    },
    "Metal Storm": {
        "vibe_sentence": "Double kicks and screaming and it still isn't loud enough.",
        "anti_mood": ["Soft Hours", "Sunday Reset", "Meditation Bath"],
    },
    "Classical Calm": {
        "vibe_sentence": "Strings and breathing room. Your brain finally unclenches.",
        "anti_mood": ["Adrenaline", "Hard Reset", "Hyperpop"],
    },
    "Rage Lift": {
        "vibe_sentence": "This rep. This weight. This rage. Now.",
        "anti_mood": ["Meditation Bath", "Sunday Reset", "Soft Hours"],
    },
    "Healing Kind": {
        "vibe_sentence": "Soft affirmations for whoever you're becoming after all that.",
        "anti_mood": ["Hard Reset", "Phonk Season", "Drill"],
    },
    "Disco Lights": {
        "vibe_sentence": "Mirrorball spinning, everyone's beautiful, and the night agrees.",
        "anti_mood": ["Rainy Window", "Hollow", "Classical Calm"],
    },
    "Amapiano Sunset": {
        "vibe_sentence": "Log drums and golden-hour groove, from South Africa to everywhere.",
        "anti_mood": ["Hard Reset", "Metal Storm", "Classical Calm"],
    },
    "Punk Sprint": {
        "vibe_sentence": "Two minutes of truth. Circle pit not optional.",
        "anti_mood": ["Meditation Bath", "Classical Calm", "Jazz Nights"],
    },
    "Dream Pop Haze": {
        "vibe_sentence": "Reverb for days. Reality got soft around the edges.",
        "anti_mood": ["Adrenaline", "Hard Reset", "Hyperpop"],
    },
    "Warehouse Techno": {
        "vibe_sentence": "Strobe ethics. Rolling kicks and tunnel vision, hours gone.",
        "anti_mood": ["Acoustic Corner", "Country Roads", "Sunday Reset"],
    },
    "Anime OST Energy": {
        "vibe_sentence": "Opening theme energy — the protagonist finally stood up.",
        "anti_mood": ["Meditation Bath", "Classical Calm", "Rainy Window"],
    },
    "Chillhop Cafe": {
        "vibe_sentence": "Jazz chords, lazy drums, and you're not in a rush anymore.",
        "anti_mood": ["Adrenaline", "Euphoric Rave", "Hard Reset"],
    },
    "Meditation Bath": {
        "vibe_sentence": "Bowls and breath and the inside of your own mind, finally quiet.",
        "anti_mood": ["Adrenaline", "Euphoric Rave", "Hyperpop"],
    },
    "Vaporwave": {
        "vibe_sentence": "Mall echoes and slowed samples from a future that got delayed.",
        "anti_mood": ["Adrenaline", "Euphoric Rave", "Gospel Fire"],
    },
    "J-Pop": {
        "vibe_sentence": "Bright hooks, idol precision, and Tokyo in the chorus.",
        "anti_mood": ["Goth / Darkwave", "Hard Reset", "Hollow"],
    },
    "J-Metal": {
        "vibe_sentence": "Visual kei chaos — idol makeup over crushing riffs.",
        "anti_mood": ["Morning Ritual", "Classical Calm", "Meditation Bath"],
    },
    "Anime Openings": {
        "vibe_sentence": "OP chills every time, even episode 47.",
        "anti_mood": ["Meditation Bath", "Classical Calm", "Hollow"],
    },
    "Anime Endings": {
        "vibe_sentence": "Credits rolling, emotional weight settling, episode not forgotten.",
        "anti_mood": ["Adrenaline", "Overflow", "K-Pop Zone"],
    },
    "Songs About Goodbye": {
        "vibe_sentence": "Leaving is its own kind of music. This is it.",
        "anti_mood": ["Overflow", "Gospel Fire", "Tropicana"],
    },
    "Songs About Home": {
        "vibe_sentence": "The town you left still lives somewhere behind your sternum.",
        "anti_mood": ["Euphoric Rave", "Phonk Season", "Hyperpop"],
    },
    "Same Vibe Different Genre": {
        "vibe_sentence": "Genre is optional. The feeling is the only genre.",
        "anti_mood": ["Hollow", "Meditation Bath"],
    },
    "3 AM Unsent Texts": {
        "vibe_sentence": "You typed it. You deleted it. Now play this instead.",
        "anti_mood": ["Overflow", "Golden Hour", "Tropicana"],
    },
    "Anti-Hero Receipts": {
        "vibe_sentence": "Petty, victorious, cold — and every bar is a receipt.",
        "anti_mood": ["Healing Kind", "Gospel Fire", "Sunday Reset"],
    },
    "Money Talks": {
        "vibe_sentence": "Bag secured. Let the volume confirm it.",
        "anti_mood": ["Hollow", "Acoustic Corner", "Classical Calm"],
    },
    "Runaway Highways": {
        "vibe_sentence": "The city in your rearview, the horizon dead ahead.",
        "anti_mood": ["Meditation Bath", "Deep Focus", "Classical Calm"],
    },
    "Drill Confessions": {
        "vibe_sentence": "Street bars that know the weight of what they're saying.",
        "anti_mood": ["Gospel Fire", "Morning Ritual", "Healing Kind"],
    },
    "Shoegaze Breakups": {
        "vibe_sentence": "Walls of guitar. The haze is the heartbreak.",
        "anti_mood": ["Overflow", "Gospel Fire", "Adrenaline"],
    },
    "Queer Dance Confetti": {
        "vibe_sentence": "Pride-floor joy — love, full volume, unapologetic.",
        "anti_mood": ["Hollow", "Rainy Window", "Hard Reset"],
    },
    "Metal Testimony": {
        "vibe_sentence": "Faith and fury — the spirit moving through crushing riffs.",
        "anti_mood": ["Meditation Bath", "Sunday Reset", "Soft Hours"],
    },
    "Bedroom Pop Diary": {
        "vibe_sentence": "Intimate vocals and words you weren't supposed to hear.",
        "anti_mood": ["Adrenaline", "Euphoric Rave", "Flex Tape"],
    },
    "Baroque Pop Melodrama": {
        "vibe_sentence": "Ornate strings around a doomed love, dressed to impress the grief.",
        "anti_mood": ["Hyperpop", "Phonk Season", "Adrenaline"],
    },
    "Sea Shanty Singalong": {
        "vibe_sentence": "Call and response on a ship that doesn't care about your problems.",
        "anti_mood": ["Meditation Bath", "Dark Pop", "Hollow"],
    },
    "Brass & Drumline Energy": {
        "vibe_sentence": "Stadium-sized bounce — the band hit and the whole section felt it.",
        "anti_mood": ["Classical Calm", "Rainy Window", "Meditation Bath"],
    },
    "Symphonic Metal Epics": {
        "vibe_sentence": "Orchestral and crushing — the quest reached its final chapter.",
        "anti_mood": ["Sunday Reset", "Lo-Fi Flow", "Meditation Bath"],
    },
    "Minimal Techno Tunnel": {
        "vibe_sentence": "Hypnotic four-on-the-floor. The next hour dissolved completely.",
        "anti_mood": ["Acoustic Corner", "Country Roads", "Gospel Fire"],
    },
    "Cloud Rap Haze": {
        "vibe_sentence": "Muted beats and blurred bars — drift through it, don't decode it.",
        "anti_mood": ["Adrenaline", "Gospel Fire", "Morning Ritual"],
    },
    "Latin Ballroom Heat": {
        "vibe_sentence": "Salsa fire and bachata warmth — dancefloor romance, no translation needed.",
        "anti_mood": ["Rainy Window", "Meditation Bath", "Hollow"],
    },
    "Afro-Fusion Golden Hour": {
        "vibe_sentence": "Amapiano warmth and groove at the moment the sun agrees with everything.",
        "anti_mood": ["Hard Reset", "Goth / Darkwave", "Hollow"],
    },
    "Hyperpop Emotional Crash": {
        "vibe_sentence": "Digital heartbreak at 180bpm — crying through the glitch.",
        "anti_mood": ["Classical Calm", "Sunday Reset", "Meditation Bath"],
    },
    "Industrial Gothic Floor": {
        "vibe_sentence": "Mechanical beats and cold glamour — the warehouse is the runway.",
        "anti_mood": ["Morning Ritual", "Gospel Fire", "Healing Kind"],
    },
    "Country Story Hour": {
        "vibe_sentence": "Small-town truth in a pickup truck with no signal and perfect bars.",
        "anti_mood": ["Euphoric Rave", "Hyperpop", "Phonk Season"],
    },
    "Kawaii Metal Sparkle": {
        "vibe_sentence": "Idol hooks over crushing riffs — adorable, and somehow terrifying.",
        "anti_mood": ["Meditation Bath", "Rainy Window", "Classical Calm"],
    },
    "Pluggnb Heartache": {
        "vibe_sentence": "Auto-Tune tears dripping over trap clouds at 2am.",
        "anti_mood": ["Morning Ritual", "Gospel Fire", "Overflow"],
    },
}

# ---------------------------------------------------------------------------
# TASK 2: 23 new mood packs with complete definitions
# ---------------------------------------------------------------------------

NEW_MOODS = {
    "Cinematic Swell": {
        "description": "Orchestral film score energy, swelling strings, emotional peaks",
        "vibe_sentence": "The music when the thing you were waiting for finally happens.",
        "anti_mood": ["Lo-Fi Flow", "Smoke & Mirrors", "Chillhop Cafe"],
        "seed_phrases": [
            "cinematic orchestral music",
            "film score playlist",
            "epic orchestral swells",
            "emotional movie music",
            "strings orchestral dramatic",
            "hans zimmer type music",
        ],
        "audio_target": {
            "energy": 0.72,
            "valence": 0.58,
            "danceability": 0.32,
            "acousticness": 0.45,
            "instrumentalness": 0.65,
            "tempo_norm": 0.55,
        },
        "audio_constraints": {
            "energy_min": 0.35,
            "energy_max": 0.95,
        },
        "forbidden_tags": ["party", "hype", "gym", "drill", "phonk", "trap"],
        "forbidden_genres": ["Hyperpop", "Electronic / Drum & Bass", "K-Pop / J-Pop"],
        "expected_tags": [
            "cinematic",
            "orchestral",
            "epic",
            "strings",
            "emotional",
            "atmospheric",
            "film_score",
            "dramatic_swell",
            "swelling_strings",
            "score",
            "climax",
            "hopeful",
            "triumphant",
            "lush_orchestration",
            "stirring",
        ],
        "preferred_macro_genres": [
            "Classical / Orchestral",
            "Ambient / Experimental",
            "Electronic / Ambient",
            "Indie / Alternative",
        ],
        "semantic_core": [
            "cinematic",
            "orchestral",
            "emotional",
            "epic",
            "atmospheric",
            "dramatic",
        ],
    },

    "Breakup Bravado": {
        "description": "Post-breakup strength anthems, better off without them energy",
        "vibe_sentence": "You don't miss them. You miss who you were pretending to be.",
        "anti_mood": ["Slow Jams", "Soft Hours", "3 AM Unsent Texts"],
        "seed_phrases": [
            "breakup strength playlist",
            "moving on anthems",
            "better off without you songs",
            "empowerment after breakup",
            "post breakup confidence",
            "done with you songs",
        ],
        "audio_target": {
            "energy": 0.68,
            "valence": 0.55,
            "danceability": 0.62,
            "acousticness": 0.2,
            "instrumentalness": 0.06,
            "tempo_norm": 0.6,
        },
        "audio_constraints": {
            "energy_min": 0.42,
            "valence_min": 0.28,
        },
        "forbidden_tags": ["sad", "cry", "hollow", "sleep", "ambient"],
        "forbidden_genres": ["Classical / Orchestral", "Ambient / Experimental", "Lo-Fi"],
        "expected_tags": [
            "confident",
            "empowering",
            "anthemic",
            "lyr_goodbye",
            "lyr_angry",
            "post_breakup",
            "moving_on",
            "independence",
            "self_worth",
            "done_with_you",
            "strength_anthem",
            "unapologetic",
            "reclaiming",
            "fierce",
            "lyr_introspective",
        ],
        "preferred_macro_genres": [
            "Pop",
            "R&B / Soul",
            "Indie / Alternative",
            "East Coast Rap",
            "West Coast Rap",
        ],
        "semantic_core": [
            "confident",
            "empowering",
            "rebellious",
            "emotional",
            "celebratory",
        ],
    },

    "Campfire Sessions": {
        "description": "Acoustic guitar around the fire, singalong folk warmth",
        "vibe_sentence": "Smoke in your hair and everyone knows the words.",
        "anti_mood": ["Warehouse Techno", "Euphoric Rave", "Phonk Season"],
        "seed_phrases": [
            "campfire songs playlist",
            "acoustic singalong folk",
            "campfire acoustic music",
            "folk singalong songs",
            "bonfire music playlist",
            "campfire guitar songs",
        ],
        "audio_target": {
            "energy": 0.5,
            "valence": 0.65,
            "danceability": 0.45,
            "acousticness": 0.82,
            "instrumentalness": 0.08,
            "tempo_norm": 0.48,
        },
        "audio_constraints": {
            "energy_max": 0.78,
            "valence_min": 0.35,
        },
        "forbidden_tags": ["hype", "gym", "party", "electronic", "drill", "phonk"],
        "forbidden_genres": [
            "Electronic / Techno",
            "Electronic / Drum & Bass",
            "Hyperpop",
            "Metal",
        ],
        "expected_tags": [
            "acoustic",
            "folk",
            "singalong",
            "campfire",
            "warm",
            "communal",
            "guitar",
            "bonfire",
            "organic",
            "lyr_love",
            "lyr_introspective",
            "americana",
            "country_folk",
            "firelight",
            "intimate_group",
        ],
        "preferred_macro_genres": [
            "Folk / Americana",
            "Country",
            "Indie / Alternative",
        ],
        "semantic_core": [
            "warm",
            "communal",
            "acoustic",
            "organic",
            "nostalgic",
        ],
    },

    "Running Fuel": {
        "description": "Cardio running energy, consistent driving beat, motivational",
        "vibe_sentence": "Mile three and the playlist just pulled you through it.",
        "anti_mood": ["Meditation Bath", "Classical Calm", "Jazz Nights"],
        "seed_phrases": [
            "running playlist",
            "cardio music",
            "jogging songs",
            "run faster playlist",
            "5k run music",
            "marathon running songs",
        ],
        "audio_target": {
            "energy": 0.82,
            "valence": 0.65,
            "danceability": 0.75,
            "acousticness": 0.05,
            "instrumentalness": 0.12,
            "tempo_norm": 0.72,
        },
        "audio_constraints": {
            "energy_min": 0.6,
            "tempo_norm_min": 0.55,
        },
        "forbidden_tags": ["sad", "sleep", "ambient", "chill", "slow"],
        "forbidden_genres": [
            "Classical / Orchestral",
            "Jazz / Blues",
            "Lo-Fi",
            "Ambient / Experimental",
        ],
        "expected_tags": [
            "energetic",
            "running",
            "cardio",
            "motivational",
            "high_energy",
            "lyr_hype",
            "driving_beat",
            "consistent_tempo",
            "rhythm_locked",
            "push_through",
            "endurance",
            "pace_setter",
            "momentum",
            "miles_on_miles",
            "steady_power",
        ],
        "preferred_macro_genres": [
            "Electronic / House",
            "Pop",
            "East Coast Rap",
            "Southern Rap",
            "Electronic / Drum & Bass",
            "Rock",
        ],
        "semantic_core": [
            "energy",
            "hype",
            "motivational",
            "rhythmic",
            "powerful",
        ],
    },

    "Grief Wave": {
        "description": "Processing loss slowly, heavy and tender, not angry",
        "vibe_sentence": "Grief doesn't rush. Neither does this playlist.",
        "anti_mood": ["Overflow", "Adrenaline", "Tropicana"],
        "seed_phrases": [
            "grief playlist",
            "songs about loss",
            "mourning music",
            "sad songs about death",
            "processing grief songs",
            "funeral playlist gentle",
        ],
        "audio_target": {
            "energy": 0.22,
            "valence": 0.18,
            "danceability": 0.28,
            "acousticness": 0.58,
            "instrumentalness": 0.22,
            "tempo_norm": 0.35,
        },
        "audio_constraints": {
            "energy_max": 0.55,
            "valence_max": 0.5,
        },
        "forbidden_tags": ["party", "hype", "gym", "summer", "dance", "euphoric"],
        "forbidden_genres": [
            "Electronic / Techno",
            "Hyperpop",
            "Latin / Reggaeton",
            "Electronic / Drum & Bass",
        ],
        "expected_tags": [
            "sad",
            "melancholic",
            "tender",
            "lyr_sad",
            "lyr_introspective",
            "grief",
            "loss",
            "mourning",
            "gentle_sadness",
            "slow_tears",
            "heavy_heart",
            "processing",
            "bittersweet",
            "memorial",
            "quiet_sorrow",
        ],
        "preferred_macro_genres": [
            "Folk / Americana",
            "Indie / Alternative",
            "Classical / Orchestral",
            "R&B / Soul",
        ],
        "semantic_core": [
            "sad",
            "tender",
            "introspective",
            "heavy",
            "quiet",
        ],
    },

    "Piano Bar": {
        "description": "Sophisticated late-night piano jazz and standards",
        "vibe_sentence": "Dim light, velvet stool, the pianist knows exactly what you need.",
        "anti_mood": ["Hard Reset", "Euphoric Rave", "Phonk Season"],
        "seed_phrases": [
            "piano bar music",
            "jazz piano standards",
            "lounge piano jazz",
            "late night piano bar",
            "sophisticated jazz playlist",
            "piano jazz standards",
        ],
        "audio_target": {
            "energy": 0.3,
            "valence": 0.5,
            "danceability": 0.42,
            "acousticness": 0.72,
            "instrumentalness": 0.5,
            "tempo_norm": 0.42,
        },
        "audio_constraints": {
            "energy_max": 0.65,
        },
        "forbidden_tags": ["hype", "gym", "party", "drill", "phonk", "trap"],
        "forbidden_genres": [
            "Metal",
            "Hyperpop",
            "Electronic / Drum & Bass",
            "Electronic / Techno",
        ],
        "expected_tags": [
            "piano",
            "jazz",
            "sophisticated",
            "lounge",
            "late_night",
            "standards",
            "piano_bar",
            "cocktail_hour",
            "smoky_atmosphere",
            "velvet_sound",
            "dim_lights",
            "slow_jazz",
            "intimate",
            "brushed_drums",
            "upright_bass",
        ],
        "preferred_macro_genres": [
            "Jazz / Blues",
            "Classical / Orchestral",
            "R&B / Soul",
        ],
        "semantic_core": [
            "sophisticated",
            "chill",
            "introspective",
            "groovy",
            "night",
            "atmospheric",
        ],
    },

    "Trap & Chill": {
        "description": "Laid-back trap, hazy beats, no aggression",
        "vibe_sentence": "Trap with the anger dialed out and the haze dialed all the way up.",
        "anti_mood": ["Morning Ritual", "Gospel Fire", "Classical Calm"],
        "seed_phrases": [
            "chill trap music",
            "laid back trap beats",
            "hazy trap playlist",
            "mellow trap songs",
            "trap chill vibes",
            "slow trap beats",
        ],
        "audio_target": {
            "energy": 0.48,
            "valence": 0.38,
            "danceability": 0.65,
            "acousticness": 0.12,
            "instrumentalness": 0.28,
            "tempo_norm": 0.5,
        },
        "audio_constraints": {
            "energy_max": 0.75,
            "valence_max": 0.72,
        },
        "forbidden_tags": ["angry", "aggressive", "hype", "beast_mode", "morning"],
        "forbidden_genres": [
            "Metal",
            "Classical / Orchestral",
            "Folk / Americana",
            "Country",
        ],
        "expected_tags": [
            "chill",
            "trap",
            "hazy",
            "laid_back",
            "dark",
            "atmospheric",
            "mellow_trap",
            "trap_soul",
            "night_session",
            "cloudy_vibes",
            "head_nod",
            "zoned_out",
            "late_night_trap",
            "smooth_808",
            "no_aggression",
        ],
        "preferred_macro_genres": [
            "Southern Rap",
            "Dark R&B",
            "West Coast Rap",
            "East Coast Rap",
        ],
        "semantic_core": [
            "chill",
            "hazy",
            "introspective",
            "dark",
            "night",
        ],
    },

    "Coffee Shop Folk": {
        "description": "Indie folk in a small venue, quiet intimacy",
        "vibe_sentence": "Fifteen people in the room and the singer meant every word.",
        "anti_mood": ["Adrenaline", "Euphoric Rave", "Hard Reset"],
        "seed_phrases": [
            "coffee shop folk music",
            "indie folk acoustic cafe",
            "small venue folk playlist",
            "singer songwriter cafe",
            "quiet folk songs",
            "intimate acoustic indie",
        ],
        "audio_target": {
            "energy": 0.32,
            "valence": 0.52,
            "danceability": 0.35,
            "acousticness": 0.78,
            "instrumentalness": 0.12,
            "tempo_norm": 0.42,
        },
        "audio_constraints": {
            "energy_max": 0.65,
        },
        "forbidden_tags": ["hype", "gym", "party", "drill", "trap", "phonk"],
        "forbidden_genres": [
            "Metal",
            "Electronic / Techno",
            "Hyperpop",
            "Electronic / Drum & Bass",
        ],
        "expected_tags": [
            "folk",
            "acoustic",
            "intimate",
            "singer_songwriter",
            "coffee_shop",
            "quiet",
            "indie_folk",
            "small_venue",
            "lyr_introspective",
            "lyr_love",
            "confessional",
            "fingerpicking",
            "stripped_back",
            "whisper_close",
            "honest_lyrics",
        ],
        "preferred_macro_genres": [
            "Folk / Americana",
            "Indie / Alternative",
            "Country",
        ],
        "semantic_core": [
            "acoustic",
            "introspective",
            "intimate",
            "organic",
            "warm",
        ],
    },

    "Boxing Ring": {
        "description": "Aggressive pre-fight energy, no chill whatsoever",
        "vibe_sentence": "Walk-out music. You are about to do something irreversible.",
        "anti_mood": ["Soft Hours", "Meditation Bath", "Sunday Reset"],
        "seed_phrases": [
            "boxing walkout music",
            "fight music playlist",
            "pre fight hype songs",
            "mma entrance music",
            "aggressive combat music",
            "ring walk songs",
        ],
        "audio_target": {
            "energy": 0.94,
            "valence": 0.45,
            "danceability": 0.58,
            "acousticness": 0.03,
            "instrumentalness": 0.15,
            "tempo_norm": 0.8,
        },
        "audio_constraints": {
            "energy_min": 0.72,
        },
        "forbidden_tags": ["sad", "sleep", "chill", "ambient", "soft", "love"],
        "forbidden_genres": [
            "Jazz / Blues",
            "Classical / Orchestral",
            "Lo-Fi",
            "Ambient / Experimental",
            "Folk / Americana",
        ],
        "expected_tags": [
            "aggressive",
            "angry",
            "intense",
            "energetic",
            "lyr_hype",
            "lyr_angry",
            "fight_music",
            "walk_out",
            "combat_ready",
            "beast_mode",
            "primal",
            "dominate",
            "warrior",
            "no_mercy",
            "knockout_energy",
        ],
        "preferred_macro_genres": [
            "East Coast Rap",
            "Southern Rap",
            "Metal",
            "Punk / Hardcore",
            "Electronic / Bass & Dubstep",
            "Rock / Metal",
        ],
        "semantic_core": [
            "aggressive",
            "intense",
            "powerful",
            "hype",
            "angry",
        ],
    },

    "New City Energy": {
        "description": "Arrival excitement, exploring unknown streets, everything possible",
        "vibe_sentence": "New city. You don't know a single street yet. Perfect.",
        "anti_mood": ["Hollow", "Rainy Window", "Overthinking"],
        "seed_phrases": [
            "new city playlist",
            "exploring music",
            "moving to a new place songs",
            "arrival energy music",
            "adventure new place playlist",
            "city exploration vibes",
        ],
        "audio_target": {
            "energy": 0.7,
            "valence": 0.72,
            "danceability": 0.65,
            "acousticness": 0.18,
            "instrumentalness": 0.12,
            "tempo_norm": 0.62,
        },
        "audio_constraints": {
            "energy_min": 0.45,
            "valence_min": 0.42,
        },
        "forbidden_tags": ["sad", "sleep", "dark", "ambient", "hollow"],
        "forbidden_genres": [
            "Classical / Orchestral",
            "Ambient / Experimental",
            "Metal",
        ],
        "expected_tags": [
            "adventurous",
            "energetic",
            "hopeful",
            "lyr_hope",
            "lyr_freedom",
            "new_beginning",
            "city_exploration",
            "fresh_start",
            "arrival",
            "streets_unknown",
            "curious_energy",
            "possibilities",
            "alive_feeling",
            "metropolitan",
            "wanderer",
        ],
        "preferred_macro_genres": [
            "Pop",
            "Indie / Alternative",
            "R&B / Soul",
            "East Coast Rap",
            "Electronic / House",
        ],
        "semantic_core": [
            "hopeful",
            "energy",
            "adventurous",
            "urban",
            "celebratory",
        ],
    },

    "Acoustic Soul": {
        "description": "Acoustic guitar plus soul vocals, warm stripped-back R&B",
        "vibe_sentence": "Guitar and voice and nothing else needed to explain a thing.",
        "anti_mood": ["Hard Reset", "Warehouse Techno", "Phonk Season"],
        "seed_phrases": [
            "acoustic soul music",
            "acoustic r&b songs",
            "stripped back soul",
            "acoustic gospel soul",
            "unplugged soul music",
            "raw soul acoustic",
        ],
        "audio_target": {
            "energy": 0.4,
            "valence": 0.58,
            "danceability": 0.48,
            "acousticness": 0.72,
            "instrumentalness": 0.1,
            "tempo_norm": 0.44,
        },
        "audio_constraints": {
            "energy_max": 0.72,
        },
        "forbidden_tags": ["hype", "gym", "party", "drill", "phonk", "electronic"],
        "forbidden_genres": [
            "Metal",
            "Electronic / Techno",
            "Hyperpop",
            "Electronic / Drum & Bass",
        ],
        "expected_tags": [
            "soul",
            "acoustic",
            "warm",
            "soulful",
            "intimate",
            "lyr_love",
            "lyr_introspective",
            "acoustic_soul",
            "stripped_r&b",
            "raw_voice",
            "guitar_and_vocal",
            "organic_soul",
            "gospel_adjacent",
            "tender_delivery",
            "heartfelt",
        ],
        "preferred_macro_genres": [
            "R&B / Soul",
            "Folk / Americana",
            "Indie / Alternative",
            "Jazz / Blues",
        ],
        "semantic_core": [
            "soulful",
            "warm",
            "acoustic",
            "introspective",
            "tender",
        ],
    },

    "Retro Future": {
        "description": "80s synth pop, cassette nostalgia, neon optimism",
        "vibe_sentence": "The future the 80s imagined, running on cassette and neon hope.",
        "anti_mood": ["Acoustic Corner", "Country Roads", "Hollow"],
        "seed_phrases": [
            "80s synth pop playlist",
            "retro synthpop music",
            "new wave 80s songs",
            "cassette tape vibes",
            "neon 80s music",
            "retro pop 80s",
        ],
        "audio_target": {
            "energy": 0.68,
            "valence": 0.65,
            "danceability": 0.72,
            "acousticness": 0.05,
            "instrumentalness": 0.22,
            "tempo_norm": 0.62,
        },
        "audio_constraints": {
            "energy_min": 0.38,
            "valence_min": 0.35,
        },
        "forbidden_tags": ["dark", "drill", "phonk", "gritty", "sad"],
        "forbidden_genres": [
            "Metal",
            "Punk / Hardcore",
            "Electronic / Drum & Bass",
        ],
        "expected_tags": [
            "80s",
            "synth_pop",
            "new_wave",
            "retro",
            "neon",
            "electronic",
            "nostalgic",
            "upbeat",
            "cassette_warmth",
            "retro_future",
            "arcade_energy",
            "optimistic_synth",
            "dance_floor_80s",
            "bright_synth",
            "lyr_love",
        ],
        "preferred_macro_genres": [
            "Synthwave / Retrowave",
            "Pop",
            "Electronic / House",
            "Indie / Alternative",
        ],
        "semantic_core": [
            "nostalgic",
            "electronic",
            "warm",
            "vibrant",
            "retro",
        ],
    },

    "Winter Dark": {
        "description": "Cold isolation, grey skies, Nordic melancholy",
        "vibe_sentence": "Grey light at 3pm. Cold glass. The year winding down.",
        "anti_mood": ["Tropicana", "Overflow", "Latin Heat"],
        "seed_phrases": [
            "winter dark music",
            "nordic melancholy playlist",
            "cold isolation songs",
            "winter sad music",
            "dark winter vibes",
            "scandinavian melancholy",
        ],
        "audio_target": {
            "energy": 0.3,
            "valence": 0.2,
            "danceability": 0.32,
            "acousticness": 0.48,
            "instrumentalness": 0.35,
            "tempo_norm": 0.38,
        },
        "audio_constraints": {
            "energy_max": 0.62,
            "valence_max": 0.55,
        },
        "forbidden_tags": ["party", "hype", "summer", "tropical", "bright"],
        "forbidden_genres": [
            "Latin / Reggaeton",
            "Hyperpop",
            "K-Pop / J-Pop",
            "Electronic / Drum & Bass",
        ],
        "expected_tags": [
            "dark",
            "cold",
            "melancholic",
            "atmospheric",
            "lyr_dark",
            "lyr_sad",
            "winter_darkness",
            "nordic_feel",
            "isolation",
            "frost",
            "grey_sky",
            "empty_landscape",
            "introspective",
            "bare_trees",
            "long_night",
        ],
        "preferred_macro_genres": [
            "Indie / Alternative",
            "Folk / Americana",
            "Electronic / Ambient",
            "Ambient / Experimental",
            "Post-Punk / Darkwave",
        ],
        "semantic_core": [
            "dark",
            "cold",
            "introspective",
            "melancholic",
            "isolated",
        ],
    },

    "Protest Songs": {
        "description": "Political and activist energy, anger with purpose and direction",
        "vibe_sentence": "Anger with a destination. The sign is your chorus.",
        "anti_mood": ["Meditation Bath", "Sunday Reset", "Classical Calm"],
        "seed_phrases": [
            "protest songs playlist",
            "activist music",
            "political songs",
            "fight the power music",
            "social justice songs",
            "revolution music",
        ],
        "audio_target": {
            "energy": 0.7,
            "valence": 0.38,
            "danceability": 0.52,
            "acousticness": 0.35,
            "instrumentalness": 0.06,
            "tempo_norm": 0.58,
        },
        "audio_constraints": {
            "energy_min": 0.4,
        },
        "forbidden_tags": ["party", "hype", "flex", "luxury", "sleep"],
        "forbidden_genres": [
            "K-Pop / J-Pop",
            "Latin / Reggaeton",
            "Electronic / Techno",
        ],
        "expected_tags": [
            "protest",
            "political",
            "activist",
            "anthemic",
            "lyr_angry",
            "lyr_hope",
            "social_justice",
            "rally_cry",
            "defiant",
            "conscious_rap",
            "folk_protest",
            "revolutionary",
            "communal",
            "spoken_word",
            "truth_telling",
        ],
        "preferred_macro_genres": [
            "Folk / Americana",
            "East Coast Rap",
            "Indie / Alternative",
            "Rock / Metal",
            "R&B / Soul",
        ],
        "semantic_core": [
            "angry",
            "rebellious",
            "communal",
            "powerful",
            "authentic",
        ],
    },

    "Epic Gaming": {
        "description": "Video game OST energy, adventurous and boss-fight ready",
        "vibe_sentence": "The final boss theme started playing. You are not afraid.",
        "anti_mood": ["Meditation Bath", "Soft Hours", "Rainy Window"],
        "seed_phrases": [
            "epic gaming music",
            "video game ost playlist",
            "boss fight music",
            "game soundtrack epic",
            "adventure game music",
            "rpg battle music",
        ],
        "audio_target": {
            "energy": 0.8,
            "valence": 0.55,
            "danceability": 0.5,
            "acousticness": 0.2,
            "instrumentalness": 0.55,
            "tempo_norm": 0.68,
        },
        "audio_constraints": {
            "energy_min": 0.5,
        },
        "forbidden_tags": ["sad", "sleep", "chill", "ambient_only"],
        "forbidden_genres": [
            "Lo-Fi",
            "Country",
            "Latin / Reggaeton",
        ],
        "expected_tags": [
            "epic",
            "cinematic",
            "adventurous",
            "video_game",
            "boss_fight",
            "ost",
            "orchestral",
            "heroic",
            "battle_ready",
            "exploration_theme",
            "dramatic",
            "game_soundtrack",
            "victory_music",
            "quest_theme",
            "level_up",
        ],
        "preferred_macro_genres": [
            "Classical / Orchestral",
            "Electronic / Ambient",
            "Metal",
            "Rock / Metal",
            "Indie / Alternative",
        ],
        "semantic_core": [
            "epic",
            "adventurous",
            "cinematic",
            "powerful",
            "energy",
        ],
    },

    "Club Warm-Up": {
        "description": "Pre-peak hour, building energy, still talking but the floor is calling",
        "vibe_sentence": "10pm. The room is filling. The DJ is building something.",
        "anti_mood": ["Acoustic Corner", "Meditation Bath", "Rainy Window"],
        "seed_phrases": [
            "club warm up playlist",
            "pre party music",
            "early night club music",
            "building energy playlist",
            "pre dance floor songs",
            "warm up dj set",
        ],
        "audio_target": {
            "energy": 0.65,
            "valence": 0.62,
            "danceability": 0.74,
            "acousticness": 0.08,
            "instrumentalness": 0.3,
            "tempo_norm": 0.6,
        },
        "audio_constraints": {
            "energy_min": 0.42,
            "energy_max": 0.85,
        },
        "forbidden_tags": ["sad", "sleep", "acoustic", "folk", "ambient_only"],
        "forbidden_genres": [
            "Folk / Americana",
            "Classical / Orchestral",
            "Country",
        ],
        "expected_tags": [
            "dance",
            "club",
            "groove",
            "building",
            "warm_up",
            "pre_peak",
            "early_night",
            "still_talking",
            "dance_floor",
            "body_moving",
            "deephouse",
            "funky",
            "four_on_floor",
            "anticipation",
            "DJ_set",
        ],
        "preferred_macro_genres": [
            "Electronic / House",
            "Electronic / Techno",
            "R&B / Soul",
            "Afrobeats / Amapiano",
            "Pop",
        ],
        "semantic_core": [
            "groovy",
            "party",
            "energy",
            "night",
            "anticipation",
        ],
    },

    "Midnight Gospel": {
        "description": "Late-night existential, strange and spiritual, podcast energy",
        "vibe_sentence": "It's 2am and the universe started explaining itself.",
        "anti_mood": ["K-Pop Zone", "Latin Heat", "Adrenaline"],
        "seed_phrases": [
            "late night existential music",
            "spiritual strange playlist",
            "midnight philosophical songs",
            "cosmic music late night",
            "introspective strange vibes",
            "meditation existential music",
        ],
        "audio_target": {
            "energy": 0.28,
            "valence": 0.4,
            "danceability": 0.32,
            "acousticness": 0.45,
            "instrumentalness": 0.42,
            "tempo_norm": 0.38,
        },
        "audio_constraints": {
            "energy_max": 0.62,
        },
        "forbidden_tags": ["party", "hype", "gym", "summer", "bright"],
        "forbidden_genres": [
            "Latin / Reggaeton",
            "K-Pop / J-Pop",
            "Hyperpop",
            "Electronic / Drum & Bass",
        ],
        "expected_tags": [
            "introspective",
            "atmospheric",
            "spiritual",
            "dark",
            "lyr_introspective",
            "late_night",
            "existential",
            "cosmic",
            "strange",
            "philosophical",
            "ambient_voice",
            "meditative",
            "searching",
            "midnight_thoughts",
            "otherworldly",
        ],
        "preferred_macro_genres": [
            "Ambient / Experimental",
            "Electronic / Ambient",
            "Indie / Alternative",
            "Folk / Americana",
        ],
        "semantic_core": [
            "introspective",
            "spiritual",
            "atmospheric",
            "dark",
            "night",
        ],
    },

    "Work Mode": {
        "description": "Productive focus with energy, uptempo but not distracting",
        "vibe_sentence": "Head down, tabs open, this playlist is the only structure.",
        "anti_mood": ["Hollow", "Grief Wave", "Overthinking"],
        "seed_phrases": [
            "work playlist",
            "productive music",
            "working from home songs",
            "office music focus",
            "study with energy",
            "focus but upbeat",
        ],
        "audio_target": {
            "energy": 0.55,
            "valence": 0.58,
            "danceability": 0.52,
            "acousticness": 0.22,
            "instrumentalness": 0.38,
            "tempo_norm": 0.52,
        },
        "audio_constraints": {
            "energy_max": 0.8,
        },
        "forbidden_tags": ["party", "hype", "gym", "angry", "rave"],
        "forbidden_genres": [
            "Metal",
            "Punk / Hardcore",
            "Electronic / Drum & Bass",
        ],
        "expected_tags": [
            "focus",
            "productive",
            "work",
            "study",
            "instrumental",
            "background",
            "flow_state",
            "desk_session",
            "wfh_vibes",
            "consistent_energy",
            "not_distracting",
            "steady_tempo",
            "concentrated",
            "deep_work",
            "momentum",
        ],
        "preferred_macro_genres": [
            "Electronic / House",
            "Electronic / Ambient",
            "Lo-Fi",
            "Jazz / Blues",
            "Indie / Alternative",
        ],
        "semantic_core": [
            "focus",
            "productive",
            "energy",
            "calm",
            "rhythmic",
        ],
    },

    "Bedroom Confessions": {
        "description": "Very late, whisper-quiet, honest and small",
        "vibe_sentence": "3am honesty that would never survive the daylight.",
        "anti_mood": ["Boxing Ring", "Adrenaline", "Overflow"],
        "seed_phrases": [
            "bedroom confessions music",
            "whisper quiet songs",
            "late night honest playlist",
            "very quiet introspective songs",
            "bedroom sad whisper",
            "3am quiet confession",
        ],
        "audio_target": {
            "energy": 0.2,
            "valence": 0.28,
            "danceability": 0.3,
            "acousticness": 0.62,
            "instrumentalness": 0.18,
            "tempo_norm": 0.32,
        },
        "audio_constraints": {
            "energy_max": 0.5,
            "valence_max": 0.6,
        },
        "forbidden_tags": ["party", "hype", "gym", "summer", "bright", "energetic"],
        "forbidden_genres": [
            "Metal",
            "Hyperpop",
            "Electronic / Drum & Bass",
            "K-Pop / J-Pop",
        ],
        "expected_tags": [
            "whisper",
            "intimate",
            "introspective",
            "dark",
            "lyr_sad",
            "lyr_introspective",
            "late_night",
            "quiet_honesty",
            "confessional",
            "small_room",
            "soft_voice",
            "bare_lyric",
            "naked_truth",
            "bedroom_dark",
            "raw_quiet",
        ],
        "preferred_macro_genres": [
            "Indie / Alternative",
            "Folk / Americana",
            "R&B / Soul",
            "Dark R&B",
        ],
        "semantic_core": [
            "introspective",
            "sad",
            "intimate",
            "quiet",
            "dark",
        ],
    },

    "Sea of Feels": {
        "description": "Emotional overwhelm, tears that feel necessary and earned",
        "vibe_sentence": "You needed this cry. The playlist knew before you did.",
        "anti_mood": ["Adrenaline", "Boxing Ring", "Flex Tape"],
        "seed_phrases": [
            "emotional overwhelm playlist",
            "songs that make you cry",
            "deeply emotional music",
            "cry it out playlist",
            "overwhelming feelings songs",
            "cathartic emotional music",
        ],
        "audio_target": {
            "energy": 0.45,
            "valence": 0.22,
            "danceability": 0.35,
            "acousticness": 0.45,
            "instrumentalness": 0.12,
            "tempo_norm": 0.42,
        },
        "audio_constraints": {
            "valence_max": 0.55,
            "energy_max": 0.75,
        },
        "forbidden_tags": ["party", "hype", "gym", "summer", "dance"],
        "forbidden_genres": [
            "Electronic / Techno",
            "Hyperpop",
            "Latin / Reggaeton",
        ],
        "expected_tags": [
            "sad",
            "emotional",
            "cathartic",
            "melancholic",
            "lyr_sad",
            "lyr_introspective",
            "overwhelm",
            "cathartic_cry",
            "deeply_felt",
            "tears",
            "chest_ache",
            "necessary_sadness",
            "release",
            "heavy_heart",
            "bittersweet",
        ],
        "preferred_macro_genres": [
            "Indie / Alternative",
            "Folk / Americana",
            "R&B / Soul",
            "Pop",
            "Classical / Orchestral",
        ],
        "semantic_core": [
            "sad",
            "emotional",
            "cathartic",
            "introspective",
            "tender",
        ],
    },

    "Dance Alone": {
        "description": "Dancing in your room alone at 2am, uninhibited joy",
        "vibe_sentence": "Nobody watching. Volume up. This is the real you.",
        "anti_mood": ["Hollow", "Grief Wave", "Meditation Bath"],
        "seed_phrases": [
            "dancing alone playlist",
            "dance in your room songs",
            "private dance party",
            "bedroom dance music",
            "solo dance party songs",
            "2am dance playlist",
        ],
        "audio_target": {
            "energy": 0.75,
            "valence": 0.78,
            "danceability": 0.82,
            "acousticness": 0.1,
            "instrumentalness": 0.1,
            "tempo_norm": 0.65,
        },
        "audio_constraints": {
            "energy_min": 0.5,
            "valence_min": 0.48,
        },
        "forbidden_tags": ["sad", "sleep", "ambient", "hollow", "cry"],
        "forbidden_genres": [
            "Classical / Orchestral",
            "Ambient / Experimental",
            "Lo-Fi",
        ],
        "expected_tags": [
            "dance",
            "joy",
            "uninhibited",
            "private_dance",
            "lyr_euphoric",
            "lyr_party",
            "bedroom_bop",
            "alone_euphoria",
            "free_movement",
            "no_audience",
            "full_release",
            "groove",
            "body_moving",
            "carefree",
            "pure_fun",
        ],
        "preferred_macro_genres": [
            "Pop",
            "Electronic / House",
            "R&B / Soul",
            "Hyperpop",
            "K-Pop / J-Pop",
        ],
        "semantic_core": [
            "euphoric",
            "party",
            "happy",
            "energy",
            "vibrant",
        ],
    },

    "Rage Quit": {
        "description": "Gaming anger, pure frustration, cathartic loud release",
        "vibe_sentence": "You died to the same checkpoint twelve times. This is appropriate.",
        "anti_mood": ["Meditation Bath", "Sunday Reset", "Soft Hours"],
        "seed_phrases": [
            "rage quit playlist",
            "gaming anger music",
            "frustration songs",
            "rage music playlist",
            "cathartic anger songs",
            "scream it out playlist",
        ],
        "audio_target": {
            "energy": 0.9,
            "valence": 0.28,
            "danceability": 0.52,
            "acousticness": 0.04,
            "instrumentalness": 0.18,
            "tempo_norm": 0.78,
        },
        "audio_constraints": {
            "energy_min": 0.65,
            "valence_max": 0.6,
        },
        "forbidden_tags": ["sad", "sleep", "chill", "ambient", "soft", "love"],
        "forbidden_genres": [
            "Jazz / Blues",
            "Classical / Orchestral",
            "Lo-Fi",
            "Country",
        ],
        "expected_tags": [
            "angry",
            "aggressive",
            "intense",
            "dark",
            "lyr_angry",
            "rage",
            "frustration",
            "cathartic_release",
            "scream",
            "breakdown",
            "heavy",
            "fury",
            "no_mercy",
            "destructive_energy",
            "loud",
        ],
        "preferred_macro_genres": [
            "Metal",
            "Punk / Hardcore",
            "Emo / Post-Hardcore",
            "Electronic / Bass & Dubstep",
            "Rock / Metal",
        ],
        "semantic_core": [
            "angry",
            "intense",
            "cathartic",
            "aggressive",
            "heavy",
        ],
    },

    "Tenderness": {
        "description": "Soft love, gentle connection, warmth without drama",
        "vibe_sentence": "Love that doesn't need to announce itself.",
        "anti_mood": ["Adrenaline", "Hard Reset", "Boxing Ring"],
        "seed_phrases": [
            "tender love songs",
            "gentle love music",
            "soft romantic playlist",
            "warmth music tender",
            "quiet love songs",
            "gentle connection music",
        ],
        "audio_target": {
            "energy": 0.3,
            "valence": 0.68,
            "danceability": 0.38,
            "acousticness": 0.55,
            "instrumentalness": 0.12,
            "tempo_norm": 0.38,
        },
        "audio_constraints": {
            "energy_max": 0.6,
            "valence_min": 0.38,
        },
        "forbidden_tags": ["hype", "gym", "angry", "aggressive", "party", "drill"],
        "forbidden_genres": [
            "Metal",
            "Punk / Hardcore",
            "Hyperpop",
            "Electronic / Drum & Bass",
        ],
        "expected_tags": [
            "tender",
            "soft",
            "love",
            "gentle",
            "romantic",
            "lyr_love",
            "lyr_introspective",
            "warmth",
            "quiet_love",
            "intimate",
            "sweet",
            "caring",
            "connection",
            "undramatic",
            "soothing",
        ],
        "preferred_macro_genres": [
            "R&B / Soul",
            "Folk / Americana",
            "Indie / Alternative",
            "Pop",
        ],
        "semantic_core": [
            "love",
            "tender",
            "soft",
            "warm",
            "intimate",
        ],
    },
}


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main():
    with open(PACKS_PATH, "r", encoding="utf-8") as f:
        data = json.load(f)

    moods = data["moods"]

    # Task 1: patch existing moods
    patched = 0
    missing = []
    for mood_name, patch in EXISTING_MOOD_PATCHES.items():
        if mood_name in moods:
            moods[mood_name]["vibe_sentence"] = patch["vibe_sentence"]
            moods[mood_name]["anti_mood"] = patch["anti_mood"]
            patched += 1
        else:
            missing.append(mood_name)

    if missing:
        print(f"WARNING: {len(missing)} mood(s) not found in packs.json: {missing}")

    print(f"Patched {patched} existing moods with vibe_sentence + anti_mood.")

    # Task 2: add new moods
    added = 0
    for mood_name, mood_data in NEW_MOODS.items():
        if mood_name in moods:
            print(f"SKIP: '{mood_name}' already exists — not overwriting.")
        else:
            moods[mood_name] = mood_data
            added += 1

    print(f"Added {added} new moods.")
    print(f"Total moods now: {len(moods)}")

    with open(PACKS_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"Written to {PACKS_PATH}")


if __name__ == "__main__":
    main()
